// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbUVmXjMHPVoVYPZRncNRTVLwJV82y1I',
    appId: '1:337903642599:web:49ee035b61d3edafd9ff42',
    messagingSenderId: '337903642599',
    projectId: 'roomie-f0469',
    authDomain: 'roomie-f0469.firebaseapp.com',
    storageBucket: 'roomie-f0469.firebasestorage.app',
    measurementId: 'G-S2HWKREN5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJoFGNo61usrIKS59le-vkT2uEHHkYi2w',
    appId: '1:337903642599:android:8a09c3ac00ab7d22d9ff42',
    messagingSenderId: '337903642599',
    projectId: 'roomie-f0469',
    storageBucket: 'roomie-f0469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvm0q1ohgTxFvIB6H1V-zEBwOg8rw1cs',
    appId: '1:337903642599:ios:c58f4bafae95e3c0d9ff42',
    messagingSenderId: '337903642599',
    projectId: 'roomie-f0469',
    storageBucket: 'roomie-f0469.firebasestorage.app',
    iosBundleId: 'com.example.roomie',
  );
}
